### ISSUE TITLE
Output of APIT pretrained model has a mosaic pattern

### ISSUE THREAD

**Issue by buildist** [amanchadha/iSeeBetter#11]
When using `netG_epoch_4_1_APITLoss.pth` the output is less smooth than the L1 loss model as expected, but there's a faint mosaic pattern all over everything. Did you notice this in your research or is there a problem with my setup?

![image](https://user-images.githubusercontent.com/1991915/93905847-4af16880-fcb0-11ea-8b77-fa1782438b2e.png)

**Comment by amanchadha** [comment]
Hey,

I'd love to help you figure this out, but I'll need more detail to figure out what's up. Can you send me the parameters you're training with?

**Comment by buildist** [comment]
Thanks! I didn't train my own model using APIT loss option yet - simply used yours that is in `weights/netG_epoch_4_1_APITLoss.pth`. Just wondering if that's what you get when testing with that model.

**Comment by amanchadha** [comment]
Overall, your output looks reasonable to me. The pattern might also be an artifact of your test workload, but I think it looks in-line with the results I remember seeing when I was experimenting with iSeeBetter.

**Comment by buildist** [comment]
Cool, I'll do some more training experiments and see what I can figure out. Trying to do super-resolution combined with compression artifact reduction and I'm already getting good results from training my own model.

**Comment by amanchadha** [comment]
Good to hear! I'm open to collaborate so if you're interested in exploring that/something together, I'm down!
