### ISSUE TITLE
about the loss 

### ISSUE THREAD

**Issue by heiheihei-ops** [amanchadha/iSeeBetter#16]
Hello
I have noticed that, when calculated the G or the D loss, you have divided it by the data length in your code, is there any usage of this operation? Waiting for your answer, Thanks a lot!
https://github.com/amanchadha/iSeeBetter/blob/b2e5326779cee8dc08eab1439ea03fd243ad3173/iSeeBetterTrain.py#L110

**Comment by amanchadha** [comment]
Hi @heiheihei-ops , this corresponds to the batch size as stated in equation (7) of our paper: https://arxiv.org/pdf/2006.11161.pdf
