### ISSUE TITLE
About the loss again

### ISSUE THREAD

**Issue by heiheihei-ops** [amanchadha/iSeeBetter#18]
![image](https://user-images.githubusercontent.com/66516707/99866813-34ec1f80-2bef-11eb-9395-e043ed3b576d.png)
Thank you for your answer, but I notice you have used .mean() in your code , and I think its usage is the same as to divide by the batchsize. By the way, if it is possible to see the loss curve when you train? Thank you so much!

**Comment by amanchadha** [comment]
Hi again @heiheihei-ops , any operations on the loss would still hold well and would leave the training process relatively unaffected since we only care for the relative value of the loss (and not its absolute value). Unfortunately, I do not have the loss curve handy :(
