### ISSUE TITLE
Not Upscaling - getting the same resolution as input

### ISSUE THREAD

**Issue by nigh8w0lf** [amanchadha/iSeeBetter#21]
Using the --upscale_only switch, getting same resolution of images as input.

**Comment by SolomGfxcolor** [comment]
give me notebook for google colab Plz

**Comment by spigelli** [comment]
> give me notebook for google colab Plz

A notebook to address the --upscale_only flag?

**Comment by spigelli** [comment]
@tthg119 @amanchadha Any news on getting this fixed? I'd like to use this upscaler in a project I'm working on

**Comment by AromaticJ** [comment]
@spigelli Hi, in original code of "iSeeBetterTest.py" the parameter "--upscale_only" doesn't transformeted to "dataset.py" and "data.py"。 You can follow the steps below to fix this error
iSeeBetterTest.py revise:
1. replace line38 with:parser.add_argument('-u', '--upscale_only', type=bool, default=True, help="Upscale mode - without downscaling.")
2. repalce line56 with:test_set = get_test_set(args.data_dir, args.nFrames, args.upscale_factor, args.file_list, args.other_dataset, args.future_frame, args.upscale_only)

data.py revise:
1.replace line24 with:def get_test_set(data_dir, nFrames, upscale_factor, file_list, other_dataset, future_frame, upscale_only):
2.replace line25 with:return DatasetFromFolderTest(data_dir, nFrames, upscale_factor, file_list, other_dataset, future_frame, transform=transform(), upscale_only=upscale_only)

**Comment by amanchadha** [comment]
Thanks @AromaticJ  for the fixes!

@spigelli , @nigh8w0lf : I've just pushed a commit with the fixes. Note that you will need to pass in -u for the upscale only mode to work (iSeeBetter is not set to 'upscale only' by default).
