### ISSUE TITLE
module 'pyflow' has no attribute 'coarse2fine_flow'

### ISSUE THREAD

**Issue by thijsheijden** [amanchadha/iSeeBetter#23]
Hey there! I keep getting the following error:
`module 'pyflow' has no attribute 'coarse2fine_flow'`
when trying to run `python3.7 iSeeBetterTest.py`

I am using python 3.7.9 with all the corresponding packages. My torch install however is version 1.7.1 as the version in requirements.txt does not seem to exist? Anyone that can help me?

**Comment by harem-token** [comment]
Did you try building pyflow from scratch?

**Comment by thijsheijden** [comment]
Yes, it built successfully and the demo worked. Got the same error. Maybe I should try cloning the latest pyflow version and see if that will work.

**Comment by thijsheijden** [comment]
Okay, after rebuilding pyflow I still get the same error. Here are the pip installs I am using, perhaps this is due to a wrong version in one of the installs?

- absl-py              0.11.0
- asn1crypto           0.24.0
- astor                0.8.1
- attrs                17.4.0
- Automat              0.6.0
- certifi              2018.1.18
- chardet              3.0.4
- click                6.7
- colorama             0.3.7
- command-not-found    0.3
- configobj            5.0.6
- constantly           15.1.0
- cryptography         2.1.4
- cycler               0.10.0
- Cython               0.29.21
- decorator            4.4.2
- distro-info          0.18ubuntu0.18.04.1
- gast                 0.2.2
- google-pasta         0.2.0
- grpcio               1.35.0
- h5py                 2.10.0
- httplib2             0.9.2
- hyperlink            17.3.1
- idna                 2.6
- imageio              2.9.0
- importlib-metadata   3.4.0
- incremental          16.10.1
- iotop                0.6
- Keras-Applications   1.0.8
- Keras-Preprocessing  1.1.2
- kiwisolver           1.3.1
- language-selector    0.1
- Markdown             3.3.3
- matplotlib           3.3.3
- netifaces            0.10.4
- networkx             2.5
- numpy                1.16.4
- opencv-python        4.5.1.48
- opt-einsum           3.3.0
- PAM                  0.4.2
- Pillow               8.1.0
- pip                  20.3.3
- protobuf             3.14.0
- pyasn1               0.4.2
- pyasn1-modules       0.2.1
- pygobject            3.26.1
- pyOpenSSL            17.5.0
- pyparsing            2.4.7
- pyserial             3.4
- python-apt           1.6.5+ubuntu0.5
- python-dateutil      2.8.1
- python-debian        0.1.32
- pytorch-ssim         0.1
- PyWavelets           1.1.1
- PyYAML               3.12
- requests             2.18.4
- requests-unixsocket  0.1.5
- scikit-image         0.15.0
- scipy                1.5.4
- service-identity     16.0.0
- setuptools           51.3.3
- six                  1.11.0
- ssh-import-id        5.7
- systemd-python       234
- tensorboard          1.15.0
- tensorflow-estimator 1.15.1
- tensorflow-gpu       1.15.5
- termcolor            1.1.0
- torch                1.3.0
- torchvision          0.4.1
- tqdm                 4.37.0
- Twisted              17.9.0
- typing-extensions    3.7.4.3
- ufw                  0.36
- unattended-upgrades  0.1
- urllib3              1.22
- Werkzeug             1.0.1
- wheel                0.36.2
- wrapt                1.12.1
- zipp                 3.4.0
- zope.interface       4.3.2

**Comment by cloudweather** [comment]
hi @thijsheijden 
would you mind sharing how you have solved the `AttributeError: module 'pyflow' has no attribute 'coarse2fine_flow'` error? Thank you!

**Comment by thijsheijden** [comment]
hey @cloudweather ,
if I recall correctly, after building pyflow I had to drag one of the files from the pyflow directory into the main directory (where all the iSeeBetter python files are), im not quite sure which file that was, perhaps the .pyx file or the .so files?

**Comment by mitch-volpi** [comment]
@thijsheijden @bycloudai After building pyflow as instructed in the README.md, you should be able to `import pyflow` from anywhere in your local environment after you `pip` install it, e.g. `pip install ./pyflow`
