### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './vimeo_septuplet/sequences/sep_trainlist.txt'

### ISSUE THREAD

**Issue by ojasviyadav** [amanchadha/iSeeBetter#6]
I installed all the requirements and then also downloaded the Vimeo dataset using the script that you provided : 'DatasetFetcher.py'

After that I tried to train with the command "python3 iSeeBetterTrain.py", but I got this error:

```
$ python3 iSeeBetterTrain.py
[    INFO] ==> Loading datasets
Training samples chosen: sep_trainlist.txt
Traceback (most recent call last):
  File "iSeeBetterTrain.py", line 264, in <module>
    main()
  File "iSeeBetterTrain.py", line 206, in main
    args.other_dataset, args.patch_size, args.future_frame)
  File "/home/iSeeBetter/data.py", line 17, in get_training_set
    transform=transform())
  File "/home/iSeeBetter/dataset.py", line 168, in __init__
    alist = [line.rstrip() for line in open(join(image_dir,file_list))]
FileNotFoundError: [Errno 2] No such file or directory: './vimeo_septuplet/sequences/sep_trainlist.txt'
```
How can I debug this?

**Comment by amanchadha** [comment]
Hey!

Sorry for the delayed response. IIRC, `sep_trainlist.txt` should be available from the MIT Vimeo90K dataset. If you can't find it, you can always use the other testlists in the [vimeo90K/](https://github.com/amanchadha/iSeeBetter/tree/master/vimeo90k) folder.

Hope this helps!
