### ISSUE TITLE
input 1280*720 output1280*720

### ISSUE THREAD

**Issue by EAGLE50** [amanchadha/iSeeBetter#7]
run：python iSeeBetter.py -m weights/RBPN_2X -s 2 
the size of input frame is 1280*720, I hope that I could get the output frame 2560*1440, but not.
Have I done wrong somewhere?

**Comment by amanchadha** [comment]
Hey!

Unfortunately, I haven't tried using the `RBPN_2X` model. Theoretically, I would expect it to work, with `s = 2`.

How about trying out the `4x` model that we recommend with `s = 2`? Maybe give that a shot?

Hope this help!

**Comment by Johnreidsilver** [comment]
Running the iSeeBetterTest.py the results are always the same size as the input. I imagine the input is reduced by the scaling factor and then the model predicts the original size frame from the downscaled sample, so the PSNR can be calculated.
How to output a true prediction, in other words, how to get a scaled output?

**Comment by amanchadha** [comment]
> I imagine the input is reduced by the scaling factor and then the model predicts the original size frame from the downscaled sample, so the PSNR can be calculated.
Correct. 

> How to output a true prediction, in other words, how to get a scaled output?

The upscaled output is written using `save_img()` in iSeeBetterTest.py, as follows:

```python
def save_img(img, img_name, pred_flag):
    save_img = img.squeeze().clamp(0, 1).numpy().transpose(1,2,0)

    # save img
    save_dir=os.path.join(args.output, args.data_dir, os.path.splitext(args.file_list)[0]+'_'+str(args.upscale_factor)+'x')
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
        
    if pred_flag:
        save_fn = save_dir +'/'+ img_name+'_'+args.model_type+'F'+str(args.nFrames)+'.png'
    else:
        save_fn = save_dir +'/'+ img_name+'.png'
```

**Comment by Johnreidsilver** [comment]
I believe the original poster is asking for a way to save a prediction of a higher resolution made from the input image (resulting in scale factor * resolution of input image) and not a test where the saved prediction resolution is the same as the input.

**Comment by amanchadha** [comment]
The downscaled image (of dims: input image/scale factor) can be retrieved from `input` within `dataset.py`:

> `input=target.resize((int(target.size[0]/scale),int(target.size[1]/scale)), Image.BICUBIC)`

The upscaled output (of dims: scale factor*resolution of input image) is written using `save_img()` like I mentioned in my last comment.

**Comment by Johnreidsilver** [comment]
Well it's not working on this side then. . I've tested with CPU (don't have CUDA) and get both outputs at the same resolution as the input. The prediction that is saved is clearly upscaled version of input/upscale_factor

I was thinking some option was missing from my command line to change to prediction instead of testing. Looking at the code it seems load_img in dataset.py always downscales the input image by scale

**Comment by amanchadha** [comment]
> The prediction that is saved is clearly upscaled version of input/upscale_factor.

Correct. That is intended.

> Looking at the code it seems load_img in dataset.py always downscales the input image by scale.

Again, correct and intentional.

**Comment by Johnreidsilver** [comment]
I understand it's the correct function of testing, but OP was asking for true prediction (prediction resolution = original input image resolution*scale factor) not testing (prediction resolution = original input image resolution)

**Comment by amanchadha** [comment]
Got it. A ready pipeline does not exist, but should be easily implementable by removing the down-scaling operation on `input` within `dataset.py`.

**Comment by Johnreidsilver** [comment]
Yes, thank you. Just did that after some tinkering and also disabled the PSNR function
Soon found out how little RAM I have :) but still enough for x2 scaling

**Comment by amanchadha** [comment]
Great! If you'd like to submit a pull request with your changes, you're more than welcome. Would be appreciated :)

**Comment by FeKgr** [comment]
> Yes, thank you. Just did that after some tinkering and also disabled the PSNR function
> Soon found out how little RAM I have :) but still enough for x2 scaling

Johnreidsilver, I tried doing what amanchadha proposed but ended up with non-matching tensor sizes the mismatch was always the same as the scaling so 2:1 or 4:1. Could you please share your modifications to dataset.py so I can replicate your working 2x scaling?
